In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('consumer_preferences.csv')
df

    Consumer_ID Preferred_Cuisine
0         U1001          American
1         U1002           Mexican
2         U1003           Mexican
3         U1004            Bakery
4         U1004         Breakfast
..          ...               ...
325       U1135          Southern
326       U1135         Ice Cream
327       U1136           Mexican
328       U1137           Mexican
329       U1138          Pizzeria

[330 rows x 2 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Consumer_ID        330 non-null    object
 1   Preferred_Cuisine  330 non-null    object
dtypes: object(2)
memory usage: 5.3+ KB

In [ ]:
df.describe()

       Consumer_ID Preferred_Cuisine
count          330               330
unique         138               101
top          U1135           Mexican
freq           103                97

In [ ]:
df.isnull().sum()

Consumer_ID          0
Preferred_Cuisine    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv(' cleaned_consumer_preferences_data.csv',index=False)

In [ ]:
df=pd.read_csv('consumers.csv')
df

,Consumer_ID,City,State,Country,Latitude,Longitude,Smoker,Drink_Level,Transportation_Method,Marital_Status,Children,Age,Occupation,Budget
0,U1001,San Luis Potosi,San Luis Potosi,Mexico,22.139997,-100.978803,No,Abstemious,On Foot,Single,Independent,23,Student,Medium
1,U1002,San Luis Potosi,San Luis Potosi,Mexico,22.150087,-100.983325,No,Abstemious,Public,Single,Independent,22,Student,Low
2,U1003,San Luis Potosi,San Luis Potosi,Mexico,22.119847,-100.946527,No,Social Drinker,Public,Single,Independent,23,Student,Low
3,U1004,Cuernavaca,Morelos,Mexico,18.867000,-99.183000,No,Abstemious,Public,Single,Independent,72,Employed,Medium
4,U1005,San Luis Potosi,San Luis Potosi,Mexico,22.183477,-100.959891,No,Abstemious,Public,Single,Independent,20,Student,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,U1134,San Luis Potosi,San Luis Potosi,Mexico,22.149654,-100.998610,No,Casual Drinker,Public,Single,Independent,21,Student,Medium
134,U1135,San Luis Potosi,San Luis Potosi,Mexico,22.170396,-100.949936,No,Casual Drinker,On Foot,Single,Kids,24,Student,Low
135,U1136,San Luis Potosi,San Luis Potosi,Mexico,22.149607,-100.997235,Yes,Social Drinker,Car,Single,Independent,22,Student,Low
136,U1137,San Luis Potosi,San Luis Potosi,Mexico,22.144803,-100.944623,No,Social Drinker,Public,Single,Independent,23,Student,Low
137,U1138,San Luis Potosi,San Luis Potosi,Mexico,22.152884,-100.939663,No,Social Drinker,Public,Single,Independent,21,Student,Medium

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Consumer_ID            138 non-null    object
 1   City                   138 non-null    object
 2   State                  138 non-null    object
 3   Country                138 non-null    object
 4   Latitude               138 non-null    float64
 5   Longitude              138 non-null    float64
 6   Smoker                 135 non-null    object
 7   Drink_Level            138 non-null    object
 8   Transportation_Method  131 non-null    object
 9   Marital_Status         134 non-null    object
 10  Children               127 non-null    object
 11  Age                    138 non-null    int64
 12  Occupation             131 non-null    object
 13  Budget                 131 non-null    object
dtypes: float64(2), int64(1), object(11)
memory usage: 15.2+ KB

In [ ]:
df.describe()

         Latitude   Longitude         Age
count  138.000000  138.000000  138.000000
mean    21.810389 -100.291857   27.297101
std      1.552529    0.869916   14.655364
min     18.813348 -101.054680   18.000000
25%     22.126030 -100.983000   21.000000
50%     22.150497 -100.937788   23.000000
75%     22.186642  -99.183251   25.000000
max     23.771030  -99.067106   82.000000

In [ ]:
df.isnull().sum()

Consumer_ID               0
City                      0
State                     0
Country                   0
Latitude                  0
Longitude                 0
Smoker                    3
Drink_Level               0
Transportation_Method     7
Marital_Status            4
Children                 11
Age                       0
Occupation                7
Budget                    7
dtype: int64

In [ ]:
df['Smoker'].fillna('Yes',inplace=True)
df['Transportation_Method'].fillna('Public Transportation',inplace=True)
df['Marital_Status'].fillna('Married',inplace=True)
df['Occupation'].fillna('Student',inplace=True)
df['Budget'].fillna('Medium',inplace=True)
df['Children'].fillna('Independent',inplace=True)

/tmp/ipykernel_3932/615980911.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Smoker'].fillna('Yes',inplace=True)
/tmp/ipykernel_3932/615980911.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Transportation_Method'].fillna('Public Transportation',inplace=True)
/tmp/ipykernel_3932/615980911.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marital_Status'].fillna('Married',inplace=True)
/tmp/ipykernel_3932/615980911.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Occupation'].fillna('Student',inplace=True)
/tmp/ipykernel_3932/615980911.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Budget'].fillna('Medium',inplace=True)
/tmp/ipykernel_3932/615980911.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Children'].fillna('Independent',inplace=True)

In [ ]:
df

,Consumer_ID,City,State,Country,Latitude,Longitude,Smoker,Drink_Level,Transportation_Method,Marital_Status,Children,Age,Occupation,Budget
0,U1001,San Luis Potosi,San Luis Potosi,Mexico,22.139997,-100.978803,No,Abstemious,On Foot,Single,Independent,23,Student,Medium
1,U1002,San Luis Potosi,San Luis Potosi,Mexico,22.150087,-100.983325,No,Abstemious,Public,Single,Independent,22,Student,Low
2,U1003,San Luis Potosi,San Luis Potosi,Mexico,22.119847,-100.946527,No,Social Drinker,Public,Single,Independent,23,Student,Low
3,U1004,Cuernavaca,Morelos,Mexico,18.867000,-99.183000,No,Abstemious,Public,Single,Independent,72,Employed,Medium
4,U1005,San Luis Potosi,San Luis Potosi,Mexico,22.183477,-100.959891,No,Abstemious,Public,Single,Independent,20,Student,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,U1134,San Luis Potosi,San Luis Potosi,Mexico,22.149654,-100.998610,No,Casual Drinker,Public,Single,Independent,21,Student,Medium
134,U1135,San Luis Potosi,San Luis Potosi,Mexico,22.170396,-100.949936,No,Casual Drinker,On Foot,Single,Kids,24,Student,Low
135,U1136,San Luis Potosi,San Luis Potosi,Mexico,22.149607,-100.997235,Yes,Social Drinker,Car,Single,Independent,22,Student,Low
136,U1137,San Luis Potosi,San Luis Potosi,Mexico,22.144803,-100.944623,No,Social Drinker,Public,Single,Independent,23,Student,Low
137,U1138,San Luis Potosi,San Luis Potosi,Mexico,22.152884,-100.939663,No,Social Drinker,Public,Single,Independent,21,Student,Medium

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('cleaned_consumers_data.csv',index=False)

In [ ]:
df=pd.read_csv('data_dictionary.csv')
df

,Table,Field,Description
0,Consumers,Consumer_ID,Unique identifier for each consumer
1,NaN,City,City where the consumer lives
2,NaN,State,State where the consumer lives
3,NaN,Country,Country where the consumer lives
4,NaN,Latitude,Latitude where the consumer lives
5,NaN,Longitude,Longitude where the consumer lives
6,NaN,Smoker,Whether the consumer smokes or not
7,NaN,Drink_Level,"Whether the consumer is an abstemious, causal,..."
8,NaN,Transportation_Method,"Whether the consumer transports on foot, by pu..."
9,NaN,Marital_Status,The consumer's marital status (single or married)
10,NaN,Children,Whether the consumer has dependent/independent...
11,NaN,Age,The consumer's age
12,NaN,Occupation,"The consumer's occupation (student, employed, ..."
13,NaN,Budget,"The consumer's budget (low, medium, high)"
14,Consumer_Preferences,Preferred_Cuisine,Types of food the consumer prefers
15,Ratings,Overall_Rating,The overall rating by the consumer for the res...
16,NaN,Food_Rating,The food's rating by the consumer for the rest...
17,NaN,Service_Rating,The service rating by the consumer for the res...
18,Restaurants,Restaurant_ID,Unique identifier for each restaurant
19,NaN,Name,The restaurant's name
20,NaN,City,The restaurant's city
21,NaN,State,The restaurant's state
22,NaN,Country,The restaurant's country
23,NaN,Zip_Code,The restaurat's zip code
24,NaN,Latitude,The restaurant's latitude
25,NaN,Longitude,The restaurant's longitude
26,NaN,Alcohol_Service,"Whether the restaurant seves no alcohol, wine ..."
27,NaN,Smoking_Allowed,"Whether any smoking is allowed, including in t..."
28,NaN,Price,"The restaurant's price (low, medium, high)"
29,NaN,Franchise,Whether the restaurant is a franchise
30,NaN,Area,Whether the restaurant is in an open or closed...
31,NaN,Parking,Whether the restaurant offers any sort of park...
32,Restaurant_Cuisines,Cuisine,Types of food the restaurant serves

In [ ]:
df.isnull().sum()

Table          28
Field           0
Description     0
dtype: int64

In [ ]:
df['Table'].fillna('Consumer Preferences',inplace=True)
df

/tmp/ipykernel_3932/1813875012.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Table'].fillna('Consumer Preferences',inplace=True)

,Table,Field,Description
0,Consumers,Consumer_ID,Unique identifier for each consumer
1,Consumer Preferences,City,City where the consumer lives
2,Consumer Preferences,State,State where the consumer lives
3,Consumer Preferences,Country,Country where the consumer lives
4,Consumer Preferences,Latitude,Latitude where the consumer lives
5,Consumer Preferences,Longitude,Longitude where the consumer lives
6,Consumer Preferences,Smoker,Whether the consumer smokes or not
7,Consumer Preferences,Drink_Level,"Whether the consumer is an abstemious, causal,..."
8,Consumer Preferences,Transportation_Method,"Whether the consumer transports on foot, by pu..."
9,Consumer Preferences,Marital_Status,The consumer's marital status (single or married)
10,Consumer Preferences,Children,Whether the consumer has dependent/independent...
11,Consumer Preferences,Age,The consumer's age
12,Consumer Preferences,Occupation,"The consumer's occupation (student, employed, ..."
13,Consumer Preferences,Budget,"The consumer's budget (low, medium, high)"
14,Consumer_Preferences,Preferred_Cuisine,Types of food the consumer prefers
15,Ratings,Overall_Rating,The overall rating by the consumer for the res...
16,Consumer Preferences,Food_Rating,The food's rating by the consumer for the rest...
17,Consumer Preferences,Service_Rating,The service rating by the consumer for the res...
18,Restaurants,Restaurant_ID,Unique identifier for each restaurant
19,Consumer Preferences,Name,The restaurant's name
20,Consumer Preferences,City,The restaurant's city
21,Consumer Preferences,State,The restaurant's state
22,Consumer Preferences,Country,The restaurant's country
23,Consumer Preferences,Zip_Code,The restaurat's zip code
24,Consumer Preferences,Latitude,The restaurant's latitude
25,Consumer Preferences,Longitude,The restaurant's longitude
26,Consumer Preferences,Alcohol_Service,"Whether the restaurant seves no alcohol, wine ..."
27,Consumer Preferences,Smoking_Allowed,"Whether any smoking is allowed, including in t..."
28,Consumer Preferences,Price,"The restaurant's price (low, medium, high)"
29,Consumer Preferences,Franchise,Whether the restaurant is a franchise
30,Consumer Preferences,Area,Whether the restaurant is in an open or closed...
31,Consumer Preferences,Parking,Whether the restaurant offers any sort of park...
32,Restaurant_Cuisines,Cuisine,Types of food the restaurant serves

In [ ]:
df.isnull().sum()

Table          0
Field          0
Description    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('cleaned_data_dictionary.csv',index=False)

In [ ]:
df=pd.read_csv('restaurants.csv')
df

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,NaN
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.136253,-100.933585,NaN,No,Low,No,Closed,NaN
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant_ID    130 non-null    int64
 1   Name             130 non-null    object
 2   City             130 non-null    object
 3   State            130 non-null    object
 4   Country          130 non-null    object
 5   Zip_Code         56 non-null     float64
 6   Latitude         130 non-null    float64
 7   Longitude        130 non-null    float64
 8   Alcohol_Service  43 non-null     object
 9   Smoking_Allowed  130 non-null    object
 10  Price            130 non-null    object
 11  Franchise        130 non-null    object
 12  Area             130 non-null    object
 13  Parking          65 non-null     object
dtypes: float64(3), int64(1), object(10)
memory usage: 14.3+ KB

In [ ]:
df.isnull().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking            65
dtype: int64

In [ ]:
df['Alcohol_Service'].fillna('No',inplace=True)
df['Zip_Code'].fillna('11372',inplace=True)
df['Parking'].fillna('Street Parking',inplace=True)
df

/tmp/ipykernel_3932/326754054.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alcohol_Service'].fillna('No',inplace=True)
/tmp/ipykernel_3932/326754054.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Zip_Code'].fillna('11372',inplace=True)
/tmp/ipykernel_3932/326754054.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '11372' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Zip_Code'].fillna('11372',inplace=True)
/tmp/ipykernel_3932/326754054.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Parking'].fillna('Street Parking',inplace=True)

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,11372,23.752304,-99.166913,No,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,11372,23.726819,-99.126506,No,No,Low,No,Closed,Street Parking
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,11372,23.730925,-99.145185,No,No,Low,No,Closed,Street Parking
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,11372,22.141647,-100.992712,No,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,No,No,Low,Yes,Closed,Street Parking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,11372,18.876011,-99.219890,No,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,11372,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,Street Parking
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,11372,22.136253,-100.933585,No,No,Low,No,Closed,Street Parking
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,11372,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,Street Parking

In [ ]:
df.isnull().sum()

Restaurant_ID      0
Name               0
City               0
State              0
Country            0
Zip_Code           0
Latitude           0
Longitude          0
Alcohol_Service    0
Smoking_Allowed    0
Price              0
Franchise          0
Area               0
Parking            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('cleaned_restaurants_data.csv',index=False)